#!/usr/bin/env python
# -*- coding: utf-8 -*-
import urllib2
import sys

try:
    resp = urllib2.urlopen(
        "https://api.nordvpn.com/v1/servers/countries",
        timeout=15,
    )
    data = resp.read()
    with open("/tmp/nordvpn_countries.json", "w") as f:
        f.write(data)
    sys.exit(0)
except Exception as e:
    sys.stderr.write("ERROR: %s\n" % str(e))
    sys.exit(1)
